# Plugins loaded after vim is launced
[[plugins]]
repo = 'tacroe/unite-mark'

[[plugins]]
repo = 'vim-scripts/Visual-Mark'

[[plugins]]
repo = 'thinca/vim-quickrun'
# exec command. howto: :QuickRun

[[plugins]] # python
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]] # python pep8
repo = 'dense-analysis/ale'
hook_add = '''
" ale
let g:python3_host_prog = system("which python3")
let g:ale_linters = {
    \ 'python': ['flake8'],
    \ }
let g:ale_fixers = {
    \ 'python': ['autopep8', 'black', 'isort'],
    \ }
let g:ale_python_flake8_executable = g:python3_host_prog
let g:ale_python_flake8_options = '-m flake8'
let g:ale_python_autopep8_executable = g:python3_host_prog
let g:ale_python_autopep8_options = '-m autopep8'
let g:ale_python_isort_executable = g:python3_host_prog
let g:ale_python_isort_options = '-m isort'
let g:ale_python_black_executable = g:python3_host_prog
let g:ale_python_black_options = '-m black'
" nmap <silent> <Leader>x <Plug>(ale_fix)
let g:ale_fix_on_save = 1
'''
on_ft = ['python']

[[plugins]]
repo = 'goldie-lin/vim-dts'

[[plugins]] # html css
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
nnoremap <C-e> :WinResizerStartResize<CR>
'''
