linux:
  main:
    cmd: 'cp'
    args: '$CONF_DIR/zsh/z* $HOME/.zprezto/runcoms'
mac:
  main:
    cmd: 'cp'
    args: '$CONF_DIR/config/zsh/z* $HOME/.zprezto/runcoms'
windows:
  main:
    cmd: 'echo'
    args: 'no support'
