linux:
  main:
    cmd: 'cp'
    args: '../../../config/zsh/z* ~/.zprezto/runcoms'
mac:
  main:
    cmd: 'cp'
    args: '../../../config/zsh/z* ~/.zprezto/runcoms'
windows:
  main:
    cmd: 'echo'
    args: 'no support'
