linux:
  main:
    cmd: 'cp'
    args: '$CONF_DIR/zsh/z* $HOME/.zprezto/runcoms'
  posthook:
    cmd: 'cp'
    args: '$COND_DIR/zsh/zusage $HOME/.zusage'
mac:
  main:
    cmd: 'cp'
    args: '$CONF_DIR/zsh/z* $HOME/.zprezto/runcoms'
  posthook:
    cmd: 'cp'
    args: '$COND_DIR/zsh/zusage $HOME/.zusage'
windows:
  main:
    cmd: 'echo'
    args: 'no support'
