linux:
  prehook:
    cmd: 'mkdir'
    args: '-p $HOME_CONF/nvim'
  main:
    cmd: 'cp'
    args: '$CONF_DIR/vim/init.vim $HOME_CONF/nvim/init.vim'
  posthook:
    cmd: 'cp'
    args: '$CONF_DIR/vim/*.toml $HOME_CONF/nvim'
mac:
  prehook:
    cmd: 'mkdir'
    args: '-p $HOME_CONF/nvim'
  main:
    cmd: 'cp'
    args: '$CONF_DIR/vim/init.vim $HOME_CONF/nvim/init.vim'
  posthook:
    cmd: 'cp'
    args: '$CONF_DIR/vim/*.toml $HOME_CONF/nvim'
windows:
  prehook:
    cmd: 'mkdir'
    args: '-p $HOME_CONF\\nvim'
  main:
    cmd: 'cp'
    args: '$CONF_DIR\\vim\\init.vim $HOME_CONF\\nvim\\init.vim'
  posthook:
    cmd: 'cp'
    args: '$CONF_DIR\\vim\\*.toml $HOME_CONF\\nvim'
