linux:
  main:
    cmd: 'cp'
    args: '$CONF_DIR/vim/init.vim $HOME/.vimrc'
  posthook:
    cmd: 'cp'
    args: '$CONF_DIR/vim/*.toml $HOME'
mac:
  main:
    cmd: 'cp'
    args: '$CONF_DIR/vim/init.vim $HOME/.vimrc'
  posthook:
    cmd: 'cp'
    args: '$CONF_DIR/vim/*.toml $HOME'
windows:
  main:
    cmd: 'cp'
    args: '$CONF_DIR\\vim\\init.vim $HOME\\.vimrc'
  posthook:
    cmd: 'cp'
    args: '$CONF_DIR\\vim\\*.toml $HOME'
